### ISSUE TITLE
maven-clean-plugin-3.1.0.pom, status: 401 Unauthorized

### ISSUE THREAD

**Issue by tomhealey-icma** [REGnosys/rosetta-code-generators#198]
### Description

Maven install fails with error maven-clean-plugin-3.1.0.pom, status: 401 Unauthorized. Cloned https://github.com/REGnosys/rosetta-code-generators and followed updated instructions https://github.com/REGnosys/rosetta-code-generators/issues/149 but install fails.

### Expected behaviour

Maven install should report Success for all modules.

### Steps to reproduce

See instructions https://github.com/REGnosys/rosetta-code-generators/issues/149.

Java 11
maven 3+

Create new folder for your code-gen dev env, e.g. ~/dev/code-gen (on mac) or C:/dev/code-gen (on windows), or whatever path you want. These instructions will refer to the code-gen dev folder as <code-gen>.

Set up maven:

Create new .m2 folder in your <code-gen> folder, e.g. <code-gen>/.m2.
Copy https://github.com/REGnosys/rosetta-code-generators/issues/149#issuecomment-1151680983 settings.xml file into new .m2 folder, e.g. <code-gen>/.m2/settings.xml.
In the settings.xml file, update <localRepository> to your new .m2 folder, e.g. <code-gen>/.m2/repository
Note that no server user or password is required - the code generator dependencies are public.
Fork and clone the project in your own workspace, e.g. <code-gen>/github/REGnosys/rosetta-code-generators.

Maven clean and install, specifying user settings file (-s), e.g. mvn -s <code-gen>/.m2/settings.xml clean install:

maven should run successfully with no errors

## 🔥 Exception or Error

[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:3.1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:3.1.0: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:3.1.0 from/to central (https://regnosys.jfrog.io/regnosys/libs-release): authentication failed for https://regnosys.jfrog.io/regnosys/libs-release/org/apache/maven/plugins/maven-clean-plugin/3.1.0/maven-clean-plugin-3.1.0.pom, status: 401 Unauthorized -> [Help 1]
## 🌍  Your Environment

Windows 10
Maven 3.8.4
jdk-11.0.17

**Comment by hugohills-regnosys** [comment]
Hi @tomhealey-icma , thank you for raising this issue.  As you pointed out there was an issue with rosetta-code-generator  set up instructions in #149, which I have now resolved.
