### ISSUE TITLE
Python Generator - Phase 2

### ISSUE THREAD

**Issue by dschwartznyc** [REGnosys/rosetta-code-generators#279]
CloudRIsk, FT Advisory, and TradeHeader are kicking off the second phase of development of the Python code generator.  

The goals are:
- Migrate Pydantic support to v 2.5
- Complete the implementation of support for all the DSL operators
- Complete the support for the use of metadata
- Generate Python for Rosetta-defined functions

The plan is to use the 10.2.0 version of the generator codebase.

**Comment by minesh-s-patel** [comment]
That's great news @dschwartznyc. 
Please feel free to open a draft PR (even at an early a stage) and ask for some review feedback.

**Comment by dschwartznyc** [comment]
CloudRisk (@plamen-neykov), TradeHeader (@mgratacos, @manel-martos, @dcarrascosa00), and FT Advisory are looking for feedback (@minesh-s-patel @hugohills-regnosys @SimonCockx) on a proposal to use a not-yet-fully-tested version of this code to resolve the defect identified in PR [2776 ](https://github.com/finos/common-domain-model/pull/2776#event-12219285533).  The proposed approach will support the upgraded version of Pydantic (2.x) and include support for the same generator features as the current Python generator.  It passes the current and expanded scope of unit tests including the serialization test that currently fails when CDM Is built against the Rosetta version in question.  The release also provides support for Rosetta-defined functions and a more comprehensive set of operators but these capabilities need to be tested further.  Since the expanded capabilities are not advertised and there is an ongoing commitment to finish the project, we believe that the risk of releasing the additional functionality is minimal versus allowing the defect to persist until the new version is complete or the wasted cost of trying to debug a soon-to-be outdated version of the generator. 

Let us know if the approach is supported or if there are concerns or objections.
