### ISSUE TITLE
Adding native language unit tests

### ISSUE THREAD

**Issue by dschwartznyc** [REGnosys/rosetta-code-generators#301]
We (@plamen-neykov, @mgratacos, @manel-martos, @dcarrascosa00) are preparing a new release of the Python generator that will "mung" use of protected Python keywords in Rune definitions and resolve a couple of defects.  As part of the release, we would like to add the ability to exercise native Python unit tests ater building the Python generator.   The tests would be both static and generated from Rune during the build,  They would be invoked by changing the Codefresh configuration (expanding the build or adding a new phase that executes after the build).  

In addition to ensuring more stable results, the key benefit would be that catching defects when creating the generator will reduce the likelihood that other processes that use the generator (eg the CDM build) might fail.

@minesh-s-patel @SimonCockx @hugohills - thoughts?

**Comment by SimonCockx** [comment]
Hi @dschwartznyc, I think having Python tests inside this project is a great idea!

Either having an invocation inside the Codefresh file, or somehow triggering a Python process via Maven should work I think.

> that will "mung" use of protected Python keywords

At some point we enhanced the Java generator to fix keyword clashes as well as name clashes (e.g., local variables clashing with import names / parameter names / other names defined in the generated code). I think some of the tooling developed for this purpose will be reusable. Take a look at the [JavaScope](https://github.com/finos/rune-dsl/blob/0c75e696253931e954d5aea56f2463844e9896cc/rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/JavaScope.java#L31) class, which inherits from a more general `GeneratorScope` class, designed for this purpose.

The `GeneratorScope` class exposes an `isValidIdentifier` method, which you can implement to return `false` for Python keywords, after which variable names will automatically be escaped with an underscore when used correctly in your generator.

Examples of its usage can be found throughout all classes for the Java generator.

**Comment by dschwartznyc** [comment]
@SimonCockx - thanks!  We'll add it to the Codefresh file for review in the PR.

We'll also take a look at the suggestion to leverage isValidIdentifier as an alternative to parsing keywords directly.
