### ISSUE TITLE
Generation of code incomplete after unit testing

### ISSUE THREAD

**Issue by vjuge** [REGnosys/rosetta-code-generators#64]
### Description

Generated source code is missing basic 'string' type

### Expected behaviour

Using cdm distribution 2.91.2, but reproducible with older versions

Launching `generateCdm`  test should generate a valid source code, but resulting source code is missing some of the types for properties.

Problem occurs for typescript and scala. Not tested for others.

### Steps to reproduce

unpack the .rosetta files from (java) distribution in directory, ie:
`'/home/joe/Downloads/cdm-distribution-2.91.2/common-domain-model'` 

point to this folder in the unit test, for instance for typescript test:

```
	@Test
	def void generateCdm() {
		val dirs = newArrayList(
			('/home/joe/Downloads/cdm-distribution-2.91.2/common-domain-model')
		);

		val resourceSet = resourceSetProvider.get

		dirs.map[new File(it)].map[listFiles[it.name.endsWith('.rosetta')]].flatMap [
			map[Files.readAllBytes(toPath)].map[new String(it)]
		].forEach[parse(resourceSet)]

		val rosettaModels = resourceSet.resources.map[contents.filter(RosettaModel)].flatten.toList

		val generatedFiles = generator.afterGenerate(rosettaModels)

		val cdmDir = Files.createDirectories(Paths.get("cdm"))
		generatedFiles.forEach [ fileName, contents |
			Files.write(cdmDir.resolve(fileName), contents.toString.bytes)
		]
	}

```

## 🔥 Exception or Error
example of result in 'types.ts':

```
/**
 * A class to specify the Termination Events that will be deemed an Access Condition (Initial Margin CSA) or a Specified Condition (Variation Margin CSA). ISDA 2016 English Law Credit Support Deed for Initial Margin, paragraph 13, General Principles, (e)(ii). | ISDA 2016 Japanese Law Credit Support Annex for Initial Margin, paragraph 13, General Principles, (f)(ii). | ISDA 2016 New York Law Credit Support Annex for Initial Margin, paragraph 13, General Principles, (e)(ii). | ISDA 2016 Credit Support Annex for Variation Margin, paragraph 13, (e): Conditions Precedent and Secured Party’s Rights and Remedies.
 */
export interface AccessConditionsElections {
  creditEventUponMerger?: ;
  forceMajeure?: ;
  illegality?: ;
  /**
   * The elective party.
   */
  party?: CounterpartyRoleEnum;
  taxEvent?: ;
  taxEventUponMerger?: ;
}
```

> taxEvent & taxEventUponMerger should be type ```boolean```

```
/**
 * A class to specify an account as an account number alongside, optionally. an account name, an account type, an account beneficiary and a servicing party.
 */
export interface Account {
  /**
   * A reference to the party beneficiary of the account.
   */
  accountBeneficiary?: Party;
  /**
   * The name by which the account is known.
   */
  accountName?: ;
  /**
   * The account number.
   */
  accountNumber?: ;
  /**
   * The type of account, e.g. client, house.
   */
  accountType?: AccountTypeEnum;
  /**
   * A reference to the party to which the account refers to.
   */
  partyReference?: Party;
  /**
   * The reference to the legal entity that services the account, i.e. in the books of which the account is held.
   */
  servicingParty?: Party;
}
```

> accountName should be a ```FieldWithMeta<String>```

**Comment by jim-h-wang** [comment]
Hi @vjuge ,

From your example, I can see that you are probably missing the `basictypes.rosetta` and `annotations.rosetta` files from your rosetta files list. You can find these files in the [open-source Rosetta DSL project.](https://github.com/REGnosys/rosetta-dsl/tree/master/com.regnosys.rosetta.lib/src/main/java/model). 

These files contain types that are shared across all Rosetta based models and therefore is not included with the standard CDM model files. If you are looking in the CDM distribution, they can be found inside the `rosetta-lib` library jar on the class path: `/model/basictypes.rosetta` and `/model/annotations.rosetta`.

There is hint to this in `TypescriptModelObjectGeneratorTest` (in `rosetta-code-generators` repo), but agree it could be more obvious.

```
@Test
	@Disabled("Test to generate the typescript for CDM")
	def void generateCdm() {
		val dirs = newArrayList(
			('rosetta-cdm/src/main/rosetta'),
			('rosetta-dsl/com.regnosys.rosetta.lib/src/main/java/model')
		);

		val resourceSet = resourceSetProvider.get
```

**Comment by vjuge** [comment]
that was the root cause, thanks  !
