### ISSUE TITLE
unknown MetaAndTemplateFields in Typescript

### ISSUE THREAD

**Issue by vjuge** [REGnosys/rosetta-code-generators#69]
### Description

Generated ts code has the following for class `ContractualProduct`:

```typescript 

/**
 *  A class to specify the contractual products' economic terms, alongside their product identification and product taxonomy. The contractual product class is meant to be used across the pre-execution, execution and (as part of the Contract) post-execution lifecycle contexts.
 */
export interface ContractualProduct {
  /**
   * The economic terms associated with a contractual product, i.e. the set of features that are price-forming.
   */
  economicTerms?: EconomicTerms;
  meta?: MetaAndTemplateFields;
  /**
   * The product identification value(s) that might be associated with a contractual product. The CDM provides the ability to associate several product identification methods with a product.
   */
  productIdentification?: ProductIdentification;
  /**
   * The product taxonomy value(s) associated with a contractual product.
   */
  productTaxonomy?: ProductTaxonomy[];
}

``` 

with  `meta?: MetaAndTemplateFields` property, but the class is unknown, thus results in compile errors.

It is not included in the metafields file. A fix would be to add:

```typescript
export interface MetaAndTemplateFields {
	id?: string;
	key?: string;
	reference?: string;
	scheme?: string;
	globalKey?: String;
	externalKey?: String;
  }
``` 

Happy to push a PR if required :wink:

**Comment by jim-h-wang** [comment]
@vjuge 

Thanks for the offer of a PR. I shall take you up on it :)

Can you drop your code from above into line 38 of `TypescriptMetaFieldGenerator:: metaFields`? [The function](https://github.com/REGnosys/rosetta-code-generators/blob/3cf67492024bfe75ef7f78b34c3dc48d1c241b60/typescript/src/main/java/com/regnosys/rosetta/generator/typescript/object/TypescriptMetaFieldGenerator.xtend#L30:L39) should be responsible for generating the code you need.

**Comment by vjuge** [comment]
pushed a quick one :)

**Comment by vjuge** [comment]
closed after PR merged
